In [10]:
from google.colab import files

uploaded = files.upload()

Saving train-00000-of-00001.parquet to train-00000-of-00001 (1).parquet

In [11]:
!pip install -q pyarrow

import pandas as pd

file_name = list(uploaded.keys())[0]

df = pd.read_parquet(file_name)

print("Dataset loaded successfully!")
print("Shape:", df.shape)
print("Columns:", df.columns.tolist())

display(df.head())

Dataset loaded successfully!
Shape: (3185, 5)
Columns: ['text', 'article_number', 'law_name', 'law_type', 'source']

,text,article_number,law_name,law_type,source
0,المادة الأولى\n يقصد بالألفاظ والعبارات الآتية...,المادة الأولى,اللائحة التنفيذية لإجراءات الاستئناف,لائحة,moj.gov.sa
1,المادة الثانية\n ‎-١‏ تقدم مذكرة الاعتراض إلى ...,المادة الثانية,اللائحة التنفيذية لإجراءات الاستئناف,لائحة,moj.gov.sa
2,المادة الثالثة\n ‎-١‏ للدائرة مصدرة الحكم الاط...,المادة الثالثة,اللائحة التنفيذية لإجراءات الاستئناف,لائحة,moj.gov.sa
3,المادة الخامسة\n ‎-١‏ طلب الاستئناف ينقل الدعو...,المادة الخامسة (جزء 1),اللائحة التنفيذية لإجراءات الاستئناف,لائحة,moj.gov.sa
4,الجلسة بثلاثةأيام.\n ‏المادة العاشرة\n ‏الماد...,المادة الخامسة (جزء 2),اللائحة التنفيذية لإجراءات الاستئناف,لائحة,moj.gov.sa

In [12]:
print("Missing Values:")
print(df.isnull().sum())

print("\nDuplicate Rows:")
print(df.duplicated().sum())

print("\nNumber of Laws:")
print(df["law_name"].nunique())

display(
    df[["law_name", "article_number", "text", "source"]].head(20)
)

parts = df[
    df["article_number"]
    .astype(str)
    .str.contains("جزء", na=False)
]

print("Articles containing parts:", len(parts))

display(parts[["law_name", "article_number", "text"]].head(30))

Missing Values:
text              0
article_number    0
law_name          0
law_type          0
source            0
dtype: int64

Duplicate Rows:
0

Number of Laws:
71

,law_name,article_number,text,source
0,اللائحة التنفيذية لإجراءات الاستئناف,المادة الأولى,المادة الأولى\n يقصد بالألفاظ والعبارات الآتية...,moj.gov.sa
1,اللائحة التنفيذية لإجراءات الاستئناف,المادة الثانية,المادة الثانية\n ‎-١‏ تقدم مذكرة الاعتراض إلى ...,moj.gov.sa
2,اللائحة التنفيذية لإجراءات الاستئناف,المادة الثالثة,المادة الثالثة\n ‎-١‏ للدائرة مصدرة الحكم الاط...,moj.gov.sa
3,اللائحة التنفيذية لإجراءات الاستئناف,المادة الخامسة (جزء 1),المادة الخامسة\n ‎-١‏ طلب الاستئناف ينقل الدعو...,moj.gov.sa
4,اللائحة التنفيذية لإجراءات الاستئناف,المادة الخامسة (جزء 2),الجلسة بثلاثةأيام.\n ‏المادة العاشرة\n ‏الماد...,moj.gov.sa
5,اللائحة التنفيذية لإجراءات الاستئناف,المادة الخامسة,المادة الخامسةعشرة\n تحكم الدائرة في طلب الاست...,moj.gov.sa
6,اللائحة التنفيذية لإجراءات الاستئناف,المادة السادسة,المادة السادسةعشرة\n للدائرة في سبيل نظر القضي...,moj.gov.sa
7,اللائحة التنفيذية لإجراءات الاستئناف,المادة السابعة,المادة السابعةعشرة\n ‏إذا نظرت المحكمة في القض...,moj.gov.sa
8,اللائحة التنفيذية لإجراءات الاستئناف,المادة الثانية (جزء 1),المادة الثانيةوالعشرون\n ‏في الأحوال التي ينظر...,moj.gov.sa
9,اللائحة التنفيذية لإجراءات الاستئناف,المادة الثانية (جزء 2),بسقوط الحق في الاستئناف وفقاً للمادة (الثانية...,moj.gov.sa
10,اللائحة التنفيذية لإجراءات الاستئناف,المادة الثانية (جزء 3),محضر بذلك ويوقع منه ومن مدير السجن أو التوقيف...,moj.gov.sa
11,نظام التكاليف القضائية,المادة الأولى,المادة الأولى\n يكون للألفاظ والعبارات الواردة...,moj.gov.sa
12,نظام التكاليف القضائية,المادة الثانية,المادة الثانية\n تسري أحكام النظام على جميع ال...,moj.gov.sa
13,نظام التكاليف القضائية,المادة الثالثة,المادة الثالثة\n تفرض تكاليف قضائية على الدعوى...,moj.gov.sa
14,نظام التكاليف القضائية,المادة الرابعة,المادة الرابعة\n إذا قررت المحكمة شطب الدعوىء ...,moj.gov.sa
15,نظام التكاليف القضائية,المادة الخامسة,المادة الخامسة\n تُفرض على دعوى بطلان حكم التح...,moj.gov.sa
16,نظام التكاليف القضائية,المادة السادسة,المادة السادسة\n دون إخلال بما ورد في المادتين...,moj.gov.sa
17,نظام التكاليف القضائية,المادة السابعة,المادة السابعة\n ثفرض على الطلبات الآتية تكالي...,moj.gov.sa
18,نظام التكاليف القضائية,المادة الثامنة,المادة الثامنة\n ١.تُقرض‏ على الطلبات الآتية ت...,moj.gov.sa
19,نظام التكاليف القضائية,المادة التاسعة,المادة التاسعة\n إذا ترتب على الطلب تغير في تق...,moj.gov.sa

Articles containing parts: 344

,law_name,article_number,text
3,اللائحة التنفيذية لإجراءات الاستئناف,المادة الخامسة (جزء 1),المادة الخامسة\n ‎-١‏ طلب الاستئناف ينقل الدعو...
4,اللائحة التنفيذية لإجراءات الاستئناف,المادة الخامسة (جزء 2),الجلسة بثلاثةأيام.\n ‏المادة العاشرة\n ‏الماد...
8,اللائحة التنفيذية لإجراءات الاستئناف,المادة الثانية (جزء 1),المادة الثانيةوالعشرون\n ‏في الأحوال التي ينظر...
9,اللائحة التنفيذية لإجراءات الاستئناف,المادة الثانية (جزء 2),بسقوط الحق في الاستئناف وفقاً للمادة (الثانية...
10,اللائحة التنفيذية لإجراءات الاستئناف,المادة الثانية (جزء 3),محضر بذلك ويوقع منه ومن مدير السجن أو التوقيف...
40,اللائحة التنفيذية لنظام المحاكم التجارية,المادة الحادية عشرة (جزء 1),المادة الحادية عشرة : الدوائر المؤلفة من قاض و...
41,اللائحة التنفيذية لنظام المحاكم التجارية,المادة الحادية عشرة (جزء 2),كمة\n ‏المادة الرابعة عشرة : الاستعانة بالقطاع...
65,اللائحة التنفيذية لنظام المحاكم التجارية,المادة السابعة (جزء 1),المادة السابعة والأربعون : طلب الحصول أو الاطل...
66,اللائحة التنفيذية لنظام المحاكم التجارية,المادة السابعة (جزء 2),لفقرات (؟) و(38) و(1) من المادة السادسة عشرة م...
146,اللائحة التنفيذية لنظام المحاكم التجارية,المادة الثالثة (جزء 1),المادة الثالثة والخمسون بعد المائة: تقريرالخبي...
147,اللائحة التنفيذية لنظام المحاكم التجارية,المادة الثالثة (جزء 2),‏للمحكمة إذا لم تأخذ بتقرير الخبير كلياً أو جز...
225,اللائحة التنفيذية لنظام المحاكم التجارية,المادة الثامنة (جزء 1),المادة الثامنة والأربعون بعد المائتين: الحكم ف...
226,اللائحة التنفيذية لنظام المحاكم التجارية,المادة الثامنة (جزء 2),لتحقق من استيفاء البيانات والشروط: وحصراً بالد...
227,اللائحة التنفيذية لنظام المحاكم التجارية,المادة الخامسة (جزء 1),المادة الخامسة والخمسين بعد المائتين من اللائح...
228,اللائحة التنفيذية لنظام المحاكم التجارية,المادة الخامسة (جزء 2),قامة الدعوى الجماعية» والإعلان عنها في وسيلة م...
488,نظام ملكية الوحدات العقارية وفرزها وإدارتها,المادة الثامنة (جزء 1),المادة الثامنةعشرة\n ‎-١‏ تكون لجمعية الملاك ج...
489,نظام ملكية الوحدات العقارية وفرزها وإدارتها,المادة الثامنة (جزء 2),ملاك بكل تصرف يجريه المديرباسم\n الجمعية وفي ح...
490,نظام ملكية الوحدات العقارية وفرزها وإدارتها,المادة الثامنة (جزء 3),ون\n ‏دون إخلال بما تقضي به الأنظمة ذات الصلة؛...
561,نظام الرهن العقاري المسجل,المادة التاسعة (جزء 1),المادة التاسعةعشرة\n لا يصح أن يشترط في عقد ال...
562,نظام الرهن العقاري المسجل,المادة التاسعة (جزء 2),لمادة الخامسةوالعشرون\n ‏يجوز للدائن المرتهن أ...
564,نظام الرهن العقاري المسجل,المادة الثلاثون (جزء 1),المادة الثلاثون\n ‎١‏ - لحائز العقار المرهون ح...
565,نظام الرهن العقاري المسجل,المادة الثلاثون (جزء 2),لدين قد انقضى ثم عاد لأي سبب موجب لبقائه» رجع ...
566,نظام الرهن العقاري المسجل,المادة الثلاثون (جزء 3),أهليته ناب عنهوليه.‎\n ‏المادة الخامسةوالأربع...
691,نظام الأحوال الشخصية,المادة السابعة (جزء 1),المادة السابعةوالستون\n ‎-١‏ مع مراعاة حكم الم...
692,نظام الأحوال الشخصية,المادة السابعة (جزء 2),د بالولادة في عقد الزواج» فليس للرجل أن ينفي ن...
701,نظام الأحوال الشخصية,المادة الرابعة (جزء 1),المادة الرابعةوالثمانون\n ‎-١‏ يصح توكيل الزوج...
702,نظام الأحوال الشخصية,المادة الرابعة (جزء 2),الثانيةوالتسعون\n ‎-١‏ يجب على الزوج في الطلا...
712,نظام الأحوال الشخصية,المادة الثامنة (جزء 1),المادة الثامنة بعدالمائة\n ‏تفسخ المحكمة عقد ا...
713,نظام الأحوال الشخصية,المادة الثامنة (جزء 2),؟- إذا امتنع عن جماعها مدة تزيد على (أربعة) أش...
724,نظام الأحوال الشخصية,المادة الخامسة (جزء 1),المادة الخامسة والعشرون بعدالمائة\n مع مراعاة ...

In [13]:
import re

def count_article_mentions(text):
    text = str(text)
    return len(re.findall(r'المادة\s+', text))

df["article_mentions"] = df["text"].apply(count_article_mentions)

print("Rows with more than one article mention:")
print((df["article_mentions"] > 1).sum())

display(
    df[df["article_mentions"] > 1][
        ["law_name", "article_number", "article_mentions", "text"]
    ].head(30)
)

Rows with more than one article mention:
969

,law_name,article_number,article_mentions,text
1,اللائحة التنفيذية لإجراءات الاستئناف,المادة الثانية,4,المادة الثانية\n ‎-١‏ تقدم مذكرة الاعتراض إلى ...
2,اللائحة التنفيذية لإجراءات الاستئناف,المادة الثالثة,4,المادة الثالثة\n ‎-١‏ للدائرة مصدرة الحكم الاط...
3,اللائحة التنفيذية لإجراءات الاستئناف,المادة الخامسة (جزء 1),9,المادة الخامسة\n ‎-١‏ طلب الاستئناف ينقل الدعو...
4,اللائحة التنفيذية لإجراءات الاستئناف,المادة الخامسة (جزء 2),10,الجلسة بثلاثةأيام.\n ‏المادة العاشرة\n ‏الماد...
7,اللائحة التنفيذية لإجراءات الاستئناف,المادة السابعة,5,المادة السابعةعشرة\n ‏إذا نظرت المحكمة في القض...
8,اللائحة التنفيذية لإجراءات الاستئناف,المادة الثانية (جزء 1),8,المادة الثانيةوالعشرون\n ‏في الأحوال التي ينظر...
9,اللائحة التنفيذية لإجراءات الاستئناف,المادة الثانية (جزء 2),4,بسقوط الحق في الاستئناف وفقاً للمادة (الثانية...
10,اللائحة التنفيذية لإجراءات الاستئناف,المادة الثانية (جزء 3),6,محضر بذلك ويوقع منه ومن مدير السجن أو التوقيف...
18,نظام التكاليف القضائية,المادة الثامنة,2,المادة الثامنة\n ١.تُقرض‏ على الطلبات الآتية ت...
25,نظام التكاليف القضائية,المادة الخامسة,2,المادة الخامسةعشرة\n مع مراعاة ما تقضي به الفق...
28,نظام التكاليف القضائية,المادة الثامنة,2,المادة الثامنةعشرة\n مع مراعاة ما تقضي به الما...
32,نظام التكاليف القضائية,المادة الثانية,2,المادة الثانيةوالعشرون\n تعد وزارة العدل اللائ...
34,اللائحة التنفيذية لنظام المحاكم التجارية,المادة الثانية,2,المادة الثانية:السريان\n يكون تطبيق أحكام الما...
37,اللائحة التنفيذية لنظام المحاكم التجارية,المادة الخامسة,2,المادة الخامسة:اللغة\n للأطراف الاتفاق على إجر...
39,اللائحة التنفيذية لنظام المحاكم التجارية,المادة السابعة,5,المادة السابعة:الضمان\n ‎-١‏ فيما لم يرد فيه ن...
40,اللائحة التنفيذية لنظام المحاكم التجارية,المادة الحادية عشرة (جزء 1),9,المادة الحادية عشرة : الدوائر المؤلفة من قاض و...
41,اللائحة التنفيذية لنظام المحاكم التجارية,المادة الحادية عشرة (جزء 2),2,كمة\n ‏المادة الرابعة عشرة : الاستعانة بالقطاع...
43,اللائحة التنفيذية لنظام المحاكم التجارية,المادة السادسة,2,المادة السادسة عشرة : الإدارات والوحداتالمتخصص...
48,اللائحة التنفيذية لنظام المحاكم التجارية,المادة الحادية والعشرون,3,المادة الحادية والعشرون : استئناس المحكمة برأي...
49,اللائحة التنفيذية لنظام المحاكم التجارية,المادة الثانية,2,المادة الثانية والعشرون : الآراء الفنيةالاستشا...
53,اللائحة التنفيذية لنظام المحاكم التجارية,المادة السابعة,7,المادة السابعة والعشرون : أحكامعامة\n ‎-١‏ فيم...
54,اللائحة التنفيذية لنظام المحاكم التجارية,المادة الرابعة,7,المادة الرابعة والثلاثون : الفصل في الدفوع الم...
55,اللائحة التنفيذية لنظام المحاكم التجارية,المادة السابعة,2,المادة السابعةوالثلاثون :\n فيما لم يرد فيه نص...
56,اللائحة التنفيذية لنظام المحاكم التجارية,المادة الثامنة,2,المادة الثامنةوالثلاثون :\n فيما لم يرد فيه نص...
57,اللائحة التنفيذية لنظام المحاكم التجارية,المادة التاسعة,2,المادة التاسعة والثلاثون : عنوانالتبليغ\n يجب ...
59,اللائحة التنفيذية لنظام المحاكم التجارية,المادة الحادية والأربعون,2,المادة الحادية والأربعون : عنوانالتبليغ\n لا ت...
60,اللائحة التنفيذية لنظام المحاكم التجارية,المادة الثانية,2,المادة الثانية والأربعون : عنوانالتبليغ\n لا ت...
62,اللائحة التنفيذية لنظام المحاكم التجارية,المادة الرابعة,2,المادة الرابعة والأربعون : إجراءاتالتبليغ\n يش...
65,اللائحة التنفيذية لنظام المحاكم التجارية,المادة السابعة (جزء 1),10,المادة السابعة والأربعون : طلب الحصول أو الاطل...
66,اللائحة التنفيذية لنظام المحاكم التجارية,المادة السابعة (جزء 2),7,لفقرات (؟) و(38) و(1) من المادة السادسة عشرة م...

In [14]:
print(df["article_mentions"].value_counts().sort_index())

article_mentions
0        29
1      2187
2       466
3       165
4       102
5        82
6        54
7        32
8        28
9        18
10       11
12        3
13        2
14        1
15        1
52        1
59        1
110       1
111       1
Name: count, dtype: int64

In [15]:
import re

def count_article_headings(text):
    text = str(text)

    # Count "المادة" only when it appears at the beginning of a line
    headings = re.findall(
        r'(?m)^\s*[\u200f\u200e]*المادة\s+[^\n]{1,50}',
        text
    )

    return len(headings)

df["article_headings"] = df["text"].apply(count_article_headings)

print(df["article_headings"].value_counts().sort_index())

problem_rows = df[df["article_headings"] > 1]

print("Rows containing multiple probable article headings:")
print(len(problem_rows))

display(
    problem_rows[
        ["law_name", "article_number", "article_headings", "text"]
    ].head(20)
)

article_headings
0       45
1     2668
2      153
3      104
4       95
5       54
6       34
7       15
8       13
9        3
10       1
Name: count, dtype: int64
Rows containing multiple probable article headings:
472

,law_name,article_number,article_headings,text
2,اللائحة التنفيذية لإجراءات الاستئناف,المادة الثالثة,3,المادة الثالثة\n ‎-١‏ للدائرة مصدرة الحكم الاط...
3,اللائحة التنفيذية لإجراءات الاستئناف,المادة الخامسة (جزء 1),7,المادة الخامسة\n ‎-١‏ طلب الاستئناف ينقل الدعو...
4,اللائحة التنفيذية لإجراءات الاستئناف,المادة الخامسة (جزء 2),5,الجلسة بثلاثةأيام.\n ‏المادة العاشرة\n ‏الماد...
7,اللائحة التنفيذية لإجراءات الاستئناف,المادة السابعة,5,المادة السابعةعشرة\n ‏إذا نظرت المحكمة في القض...
8,اللائحة التنفيذية لإجراءات الاستئناف,المادة الثانية (جزء 1),6,المادة الثانيةوالعشرون\n ‏في الأحوال التي ينظر...
9,اللائحة التنفيذية لإجراءات الاستئناف,المادة الثانية (جزء 2),4,بسقوط الحق في الاستئناف وفقاً للمادة (الثانية...
10,اللائحة التنفيذية لإجراءات الاستئناف,المادة الثانية (جزء 3),6,محضر بذلك ويوقع منه ومن مدير السجن أو التوقيف...
32,نظام التكاليف القضائية,المادة الثانية,2,المادة الثانيةوالعشرون\n تعد وزارة العدل اللائ...
39,اللائحة التنفيذية لنظام المحاكم التجارية,المادة السابعة,4,المادة السابعة:الضمان\n ‎-١‏ فيما لم يرد فيه ن...
40,اللائحة التنفيذية لنظام المحاكم التجارية,المادة الحادية عشرة (جزء 1),4,المادة الحادية عشرة : الدوائر المؤلفة من قاض و...
49,اللائحة التنفيذية لنظام المحاكم التجارية,المادة الثانية,2,المادة الثانية والعشرون : الآراء الفنيةالاستشا...
53,اللائحة التنفيذية لنظام المحاكم التجارية,المادة السابعة,7,المادة السابعة والعشرون : أحكامعامة\n ‎-١‏ فيم...
54,اللائحة التنفيذية لنظام المحاكم التجارية,المادة الرابعة,3,المادة الرابعة والثلاثون : الفصل في الدفوع الم...
65,اللائحة التنفيذية لنظام المحاكم التجارية,المادة السابعة (جزء 1),5,المادة السابعة والأربعون : طلب الحصول أو الاطل...
72,اللائحة التنفيذية لنظام المحاكم التجارية,المادة التاسعة,2,المادة التاسعة والخمسون : الدعاوى التي يجب فيه...
74,اللائحة التنفيذية لنظام المحاكم التجارية,المادة الثانية,2,المادة الثانية والستون : المصالحة بعدالقيد\n ‏...
89,اللائحة التنفيذية لنظام المحاكم التجارية,المادة الثامنة,6,المادة الثامنة والسبعون : إجراءاتالقيد\n ‏تتول...
92,اللائحة التنفيذية لنظام المحاكم التجارية,المادة السادسة,3,المادة السادسة والثمانون : تنفيذ خطة إدارةالدع...
97,اللائحة التنفيذية لنظام المحاكم التجارية,المادة الثالثة,8,المادة الثالثة والتسعون : تنظيم الجلساتوإدارته...
107,اللائحة التنفيذية لنظام المحاكم التجارية,المادة العاشرة,2,المادة العاشرة بعد المائة: انقضاء الحكم في الط...

In [17]:
import pandas as pd
import re

# Keep original data safe
df_original = df.copy()

# Pattern: "المادة" appearing at the beginning of a line
heading_pattern = re.compile(
    r'(?m)^[ \t\u200e\u200f]*المادة\s+[^\n]+'
)

new_rows = []

for idx, row in df_original.iterrows():
    text = str(row["text"])
    matches = list(heading_pattern.finditer(text))

    # If there are 0 or 1 headings, keep the row as it is
    if len(matches) <= 1:
        new_row = row.to_dict()
        new_row["original_row"] = idx
        new_row["detected_heading"] = (
            matches[0].group().strip() if matches else None
        )
        new_rows.append(new_row)

    # If there are multiple headings, split them
    else:
        for i, match in enumerate(matches):
            start = match.start()

            if i + 1 < len(matches):
                end = matches[i + 1].start()
            else:
                end = len(text)

            article_text = text[start:end].strip()

            new_row = row.to_dict()

            # Preserve original information
            new_row["original_row"] = idx
            new_row["original_article_number"] = row["article_number"]

            # Heading detected from the actual legal text
            heading_line = match.group().strip()
            new_row["detected_heading"] = heading_line

            # Replace text with the separated article
            new_row["text"] = article_text

            new_rows.append(new_row)

# Create a new dataframe
df_split = pd.DataFrame(new_rows)

print("Original rows:", len(df_original))
print("After splitting:", len(df_split))

display(
    df_split[
        ["law_name", "article_number",
         "detected_heading", "text", "original_row"]
    ].head(20)
)

Original rows: 3185
After splitting: 4431

,law_name,article_number,detected_heading,text,original_row
0,اللائحة التنفيذية لإجراءات الاستئناف,المادة الأولى,المادة الأولى,المادة الأولى\n يقصد بالألفاظ والعبارات الآتية...,0
1,اللائحة التنفيذية لإجراءات الاستئناف,المادة الثانية,المادة الثانية,المادة الثانية\n ‎-١‏ تقدم مذكرة الاعتراض إلى ...,1
2,اللائحة التنفيذية لإجراءات الاستئناف,المادة الثالثة,المادة الثالثة,المادة الثالثة\n ‎-١‏ للدائرة مصدرة الحكم الاط...,2
3,اللائحة التنفيذية لإجراءات الاستئناف,المادة الثالثة,‏المادة الرابعة,‏المادة الرابعة\n ‏الغائب المحكوم عليه الوارد ...,2
4,اللائحة التنفيذية لإجراءات الاستئناف,المادة الثالثة,المادة (السابعة والخمسين) منالنظام.,المادة (السابعة والخمسين) منالنظام.,2
5,اللائحة التنفيذية لإجراءات الاستئناف,المادة الخامسة (جزء 1),المادة الخامسة,المادة الخامسة\n ‎-١‏ طلب الاستئناف ينقل الدعو...,3
6,اللائحة التنفيذية لإجراءات الاستئناف,المادة الخامسة (جزء 1),‏المادة السادسة,‏المادة السادسة\n ‎-١‏ إذا حكمت المحكمة بعدم ق...,3
7,اللائحة التنفيذية لإجراءات الاستئناف,المادة الخامسة (جزء 1),‏المادة السابعة,‏المادة السابعة\n ‏يجوز أمام المحكمة أن يضاف إ...,3
8,اللائحة التنفيذية لإجراءات الاستئناف,المادة الخامسة (جزء 1),‏المادة الثامنة,‏المادة الثامنة\n ‏لا يجوز إدخال أو تدخل من لم...,3
9,اللائحة التنفيذية لإجراءات الاستئناف,المادة الخامسة (جزء 1),‏المادة التاسعة,‏المادة التاسعة\n ‎-١‏ تقيد القضية بالمحكمة فو...,3
10,اللائحة التنفيذية لإجراءات الاستئناف,المادة الخامسة (جزء 1),‏المادة العاشرة,‏المادة العاشرة,3
11,اللائحة التنفيذية لإجراءات الاستئناف,المادة الخامسة (جزء 1),‏المادة الحاديةعشرة,‏المادة الحاديةعشرة\n ‏في الأحوال التي ينظر في...,3
12,اللائحة التنفيذية لإجراءات الاستئناف,المادة الخامسة (جزء 2),‏المادة العاشرة,‏المادة العاشرة,4
13,اللائحة التنفيذية لإجراءات الاستئناف,المادة الخامسة (جزء 2),‏المادة الحاديةعشرة,‏المادة الحاديةعشرة\n ‏في الأحوال التي ينظر في...,4
14,اللائحة التنفيذية لإجراءات الاستئناف,المادة الخامسة (جزء 2),‏المادة الثانيةعشرة,‏المادة الثانيةعشرة\n ‎-١‏ إذا لم يحضر طالب ال...,4
15,اللائحة التنفيذية لإجراءات الاستئناف,المادة الخامسة (جزء 2),‏المادة الثالثةعشرة,‏المادة الثالثةعشرة\n ‏إذا لم يستوف طلب الاستئ...,4
16,اللائحة التنفيذية لإجراءات الاستئناف,المادة الخامسة (جزء 2),‏المادة الرابعةعشرة,‏المادة الرابعةعشرة\n ‏دون إخلال بما ورد في ال...,4
17,اللائحة التنفيذية لإجراءات الاستئناف,المادة الخامسة,المادة الخامسةعشرة,المادة الخامسةعشرة\n تحكم الدائرة في طلب الاست...,5
18,اللائحة التنفيذية لإجراءات الاستئناف,المادة السادسة,المادة السادسةعشرة,المادة السادسةعشرة\n للدائرة في سبيل نظر القضي...,6
19,اللائحة التنفيذية لإجراءات الاستئناف,المادة السابعة,المادة السابعةعشرة,المادة السابعةعشرة\n ‏إذا نظرت المحكمة في القض...,7

In [18]:
import pandas as pd
import re

df = df_original.copy()

# Remove invisible direction characters only
def normalize_text(text):
    text = str(text)
    text = re.sub(r'[\u200e\u200f\u202a-\u202e]', '', text)
    text = re.sub(r'[ \t]+', ' ', text)
    return text.strip()

# Detect a real article heading
def detect_heading(line):
    line = normalize_text(line)

    if not line.startswith("المادة"):
        return None

    # Ignore references to another article
    reference_words = [
        "من النظام", "منالنظام",
        "من اللائحة", "مناللائحة",
        "وفقاً", "وفقا",
        "بموجب",
        "المشار إليها",
        "الواردة في",
        "المنصوص عليها"
    ]

    if any(x in line for x in reference_words):
        return None

    # Example: المادة السادسة: معيار...
    if ":" in line or "：" in line:
        heading = re.split(r'[:：]', line, maxsplit=1)[0].strip()
        return heading

    # Example: المادة الخامسة عشرة
    if len(line) <= 60:
        return line.strip(" .،؛")

    return None


def split_law(text):
    lines = str(text).splitlines()

    articles = []
    preamble = []

    current_heading = None
    current_lines = []

    for line in lines:

        heading = detect_heading(line)

        if heading:

            if current_heading is not None:
                articles.append({
                    "article_number": current_heading,
                    "text": "\n".join(current_lines).strip()
                })

            current_heading = heading
            current_lines = [normalize_text(line)]

        else:
            if current_heading is not None:
                current_lines.append(normalize_text(line))
            else:
                if line.strip():
                    preamble.append(normalize_text(line))

    if current_heading is not None:
        articles.append({
            "article_number": current_heading,
            "text": "\n".join(current_lines).strip()
        })

    return articles, preamble

In [19]:
records = []
preambles = []

for law_name, group in df.groupby("law_name", sort=False):

    # Join all pieces belonging to the same law
    full_text = "\n".join(
        group["text"].astype(str).tolist()
    )

    articles, preamble = split_law(full_text)

    law_type = group["law_type"].iloc[0]
    source = group["source"].iloc[0]

    for article in articles:
        records.append({
            "law_name": law_name,
            "law_type": law_type,
            "article_number": article["article_number"],
            "text": article["text"],
            "source": source
        })

    if preamble:
        preambles.append({
            "law_name": law_name,
            "text": "\n".join(preamble)
        })


df_articles = pd.DataFrame(records)

print("Original rows:", len(df))
print("Detected legal articles:", len(df_articles))
print("Laws:", df_articles["law_name"].nunique())
print("Laws with text before first article:", len(preambles))

display(df_articles.head(20))

Original rows: 3185
Detected legal articles: 4367
Laws: 60
Laws with text before first article: 11

,law_name,law_type,article_number,text,source
0,اللائحة التنفيذية لإجراءات الاستئناف,لائحة,المادة الأولى,المادة الأولى\nيقصد بالألفاظ والعبارات الآتية ...,moj.gov.sa
1,اللائحة التنفيذية لإجراءات الاستئناف,لائحة,المادة الثانية,المادة الثانية\n-١ تقدم مذكرة الاعتراض إلى محك...,moj.gov.sa
2,اللائحة التنفيذية لإجراءات الاستئناف,لائحة,المادة الثالثة,المادة الثالثة\n-١ للدائرة مصدرة الحكم الاطلاع...,moj.gov.sa
3,اللائحة التنفيذية لإجراءات الاستئناف,لائحة,المادة الرابعة,المادة الرابعة\nالغائب المحكوم عليه الوارد في ...,moj.gov.sa
4,اللائحة التنفيذية لإجراءات الاستئناف,لائحة,المادة الخامسة,المادة الخامسة\n-١ طلب الاستئناف ينقل الدعوى ب...,moj.gov.sa
5,اللائحة التنفيذية لإجراءات الاستئناف,لائحة,المادة السادسة,المادة السادسة\n-١ إذا حكمت المحكمة بعدم قبول ...,moj.gov.sa
6,اللائحة التنفيذية لإجراءات الاستئناف,لائحة,المادة السابعة,المادة السابعة\nيجوز أمام المحكمة أن يضاف إلى ...,moj.gov.sa
7,اللائحة التنفيذية لإجراءات الاستئناف,لائحة,المادة الثامنة,المادة الثامنة\nلا يجوز إدخال أو تدخل من لم يك...,moj.gov.sa
8,اللائحة التنفيذية لإجراءات الاستئناف,لائحة,المادة التاسعة,المادة التاسعة\n-١ تقيد القضية بالمحكمة فور وص...,moj.gov.sa
9,اللائحة التنفيذية لإجراءات الاستئناف,لائحة,المادة العاشرة,المادة العاشرة,moj.gov.sa
10,اللائحة التنفيذية لإجراءات الاستئناف,لائحة,المادة الحاديةعشرة,المادة الحاديةعشرة\nفي الأحوال التي ينظر فيها ...,moj.gov.sa
11,اللائحة التنفيذية لإجراءات الاستئناف,لائحة,المادة العاشرة,المادة العاشرة,moj.gov.sa
12,اللائحة التنفيذية لإجراءات الاستئناف,لائحة,المادة الحاديةعشرة,المادة الحاديةعشرة\nفي الأحوال التي ينظر فيها ...,moj.gov.sa
13,اللائحة التنفيذية لإجراءات الاستئناف,لائحة,المادة الثانيةعشرة,المادة الثانيةعشرة\n-١ إذا لم يحضر طالب الاستئ...,moj.gov.sa
14,اللائحة التنفيذية لإجراءات الاستئناف,لائحة,المادة الثالثةعشرة,المادة الثالثةعشرة\nإذا لم يستوف طلب الاستئناف...,moj.gov.sa
15,اللائحة التنفيذية لإجراءات الاستئناف,لائحة,المادة الرابعةعشرة,المادة الرابعةعشرة\nدون إخلال بما ورد في الفقر...,moj.gov.sa
16,اللائحة التنفيذية لإجراءات الاستئناف,لائحة,المادة الخامسةعشرة,المادة الخامسةعشرة\nتحكم الدائرة في طلب الاستئ...,moj.gov.sa
17,اللائحة التنفيذية لإجراءات الاستئناف,لائحة,المادة السادسةعشرة,المادة السادسةعشرة\nللدائرة في سبيل نظر القضية...,moj.gov.sa
18,اللائحة التنفيذية لإجراءات الاستئناف,لائحة,المادة السابعةعشرة,المادة السابعةعشرة\nإذا نظرت المحكمة في القضية...,moj.gov.sa
19,اللائحة التنفيذية لإجراءات الاستئناف,لائحة,المادة الثامنةعشرة,المادة الثامنةعشرة\nلا يجوز تأجيل الجلسة إلا ل...,moj.gov.sa

In [20]:
df_articles["article_key"] = (
    df_articles["article_number"]
    .str.replace(r'[\s\(\)\.:：]', '', regex=True)
)

duplicates = df_articles[
    df_articles.duplicated(
        subset=["law_name", "article_key"],
        keep=False
    )
]

print("Duplicate article rows:", len(duplicates))
print(
    "Duplicate article groups:",
    duplicates.groupby(["law_name", "article_key"]).ngroups
)

display(
    duplicates[
        ["law_name", "article_number", "text"]
    ].head(20)
)

Duplicate article rows: 148
Duplicate article groups: 74

,law_name,article_number,text
9,اللائحة التنفيذية لإجراءات الاستئناف,المادة العاشرة,المادة العاشرة
10,اللائحة التنفيذية لإجراءات الاستئناف,المادة الحاديةعشرة,المادة الحاديةعشرة\nفي الأحوال التي ينظر فيها ...
11,اللائحة التنفيذية لإجراءات الاستئناف,المادة العاشرة,المادة العاشرة
12,اللائحة التنفيذية لإجراءات الاستئناف,المادة الحاديةعشرة,المادة الحاديةعشرة\nفي الأحوال التي ينظر فيها ...
28,اللائحة التنفيذية لإجراءات الاستئناف,المادة السابعةوالعشرون,المادة السابعةوالعشرون\nيجب على المحكمة إذا حك...
29,اللائحة التنفيذية لإجراءات الاستئناف,المادة السابعةوالعشرون,المادة السابعةوالعشرون\nيجب على المحكمة إذا حك...
32,اللائحة التنفيذية لإجراءات الاستئناف,المادة الثلاثون,المادة الثلاثون\nتتولى دائرة الاستئناف -التي أ...
33,اللائحة التنفيذية لإجراءات الاستئناف,المادة الثلاثون,المادة الثلاثون\nتتولى دائرة الاستئناف -التي أ...
75,اللائحة التنفيذية لنظام المحاكم التجارية,المادة الرابعة عشرة,المادة الرابعة عشرة : الاستعانة بالقطاعالخاص\n...
76,اللائحة التنفيذية لنظام المحاكم التجارية,المادة الرابعة عشرة,المادة الرابعة عشرة : الاستعانة بالقطاعالخاص\n...
220,اللائحة التنفيذية لنظام المحاكم التجارية,المادة التاسعة والخمسون بعد المائة,المادة التاسعة والخمسون بعد المائة: حجيةالخبرة...
221,اللائحة التنفيذية لنظام المحاكم التجارية,المادة التاسعة والخمسون بعد المائة,المادة التاسعة والخمسون بعد المائة: حجيةالخبرة...
317,اللائحة التنفيذية لنظام المحاكم التجارية,المادة الخامسة والخمسون بعد المائتين,المادة الخامسة والخمسون بعد المائتين: طلب قيد ...
318,اللائحة التنفيذية لنظام المحاكم التجارية,المادة الخامسة والخمسون بعد المائتين,المادة الخامسة والخمسون بعد المائتين: طلب قيد ...
327,اللائحة التنفيذية لنظام المحاكم التجارية,المادة الرابعة والستون بعد المائتين,المادة الرابعة والستون بعد المائتين: الممثل في...
328,اللائحة التنفيذية لنظام المحاكم التجارية,المادة الرابعة والستون بعد المائتين,المادة الرابعة والستون بعد المائتين: الممثل في...
703,نظام الرهن العقاري المسجل,المادة السادسةوالعشرون,المادة السادسةوالعشرون\nللمرتهن حق\nلمادة الخا...
704,نظام الرهن العقاري المسجل,المادة السادسةوالعشرون,المادة السادسةوالعشرون\nللمرتهن حق تتبع العقار...
716,نظام الرهن العقاري المسجل,المادة الثامنةوالثلاثون,المادة الثامنةوالثلاثون\nإ\nلدين قد انقضى ثم ع...
717,نظام الرهن العقاري المسجل,المادة الثامنةوالثلاثون,المادة الثامنةوالثلاثون\nإذا سدد الدين أو بعضه...

In [21]:
import re
import pandas as pd

def normalize_for_compare(text):
    text = str(text)
    text = re.sub(r'[\u200e\u200f\u202a-\u202e]', '', text)
    text = re.sub(r'\s+', ' ', text)
    return text.strip()

df_articles["text_norm"] = df_articles["text"].apply(normalize_for_compare)

results = []

for (law, key), group in df_articles.groupby(["law_name", "article_key"]):

    if len(group) == 1:
        continue

    texts = group["text_norm"].tolist()

    if len(set(texts)) == 1:
        status = "Exact Duplicate"

    elif any(
        a != b and (a in b or b in a)
        for i, a in enumerate(texts)
        for j, b in enumerate(texts)
        if i < j
    ):
        status = "Contained / Partial Duplicate"

    else:
        status = "Needs Manual Review"

    results.append({
        "law_name": law,
        "article_key": key,
        "count": len(group),
        "status": status
    })

duplicate_check = pd.DataFrame(results)

print(duplicate_check["status"].value_counts())
display(duplicate_check)

status
Needs Manual Review              67
Exact Duplicate                   5
Contained / Partial Duplicate     2
Name: count, dtype: int64

,law_name,article_key,count,status
0,الأدلة الإجرائية لنظام الإثبات,المادةالثانيةوالثلاثون,2,Needs Manual Review
1,القواعد المنظمة لإجراءات الإفلاس العابرة للحدود,المادةالسابعةعشرة,2,Needs Manual Review
2,اللائحة التنفيذية لإجراءات الاستئناف,المادةالثلاثون,2,Needs Manual Review
3,اللائحة التنفيذية لإجراءات الاستئناف,المادةالحاديةعشرة,2,Needs Manual Review
4,اللائحة التنفيذية لإجراءات الاستئناف,المادةالسابعةوالعشرون,2,Needs Manual Review
...,...,...,...,...
69,نظام المعاملات المدنية,المادةالسادسةوالخمسونبعدالثلاثمائة,2,Needs Manual Review
70,نظام المعاملات المدنية,المادةالسبعونبعدالأربعمائة,2,Needs Manual Review
71,نظام مكافحة جرائم الإرهاب وتمويله,المادةالتاسعةوالعشرون,2,Needs Manual Review
72,نظام مكافحة جرائم الإرهاب وتمويله,المادةالخامسةوالخمسون,2,Needs Manual Review
73,نظام نزع ملكية العقارات للمنفعة العامة ووضع ال...,المادةالخامسةعشرة,2,Needs Manual Review

In [22]:
import pandas as pd
from difflib import SequenceMatcher

review_rows = []

manual_groups = duplicate_check[
    duplicate_check["status"] == "Needs Manual Review"
]

for _, item in manual_groups.iterrows():

    law = item["law_name"]
    key = item["article_key"]

    group = df_articles[
        (df_articles["law_name"] == law) &
        (df_articles["article_key"] == key)
    ]

    rows = group.to_dict("records")

    # Most groups contain two versions
    if len(rows) >= 2:

        text1 = rows[0]["text"]
        text2 = rows[1]["text"]

        similarity = SequenceMatcher(
            None,
            normalize_for_compare(text1),
            normalize_for_compare(text2)
        ).ratio()

        review_rows.append({
            "law_name": law,
            "article_number_1": rows[0]["article_number"],
            "text_1": text1,
            "length_1": len(text1),

            "article_number_2": rows[1]["article_number"],
            "text_2": text2,
            "length_2": len(text2),

            "similarity": round(similarity, 3),

            # Fill this manually later:
            "decision": ""
        })

manual_review = pd.DataFrame(review_rows)

display(manual_review.head())

manual_review.to_excel(
    "manual_duplicate_review.xlsx",
    index=False
)

print("Manual review cases:", len(manual_review))

,law_name,article_number_1,text_1,length_1,article_number_2,text_2,length_2,similarity,decision
0,الأدلة الإجرائية لنظام الإثبات,المادة الثانيةوالثلاثون,المادة الثانيةوالثلاثون\nيقع عبء إثبات الادعاء...,95,المادة الثانيةوالثلاثون,المادة الثانيةوالثلاثون\nفي الأحوال التي تستند...,255,0.160,
1,القواعد المنظمة لإجراءات الإفلاس العابرة للحدود,المادة السابعةعشرة,المادة السابعةعشرة\nلا يجوز افتتاح أي إجراء إف...,193,المادة السابعةعشرة,المادة السابعةعشرة\nلا يجوز افتتاح أي إجراء إف...,342,0.284,
2,اللائحة التنفيذية لإجراءات الاستئناف,المادة الثلاثون,المادة الثلاثون\nتتولى دائرة الاستئناف -التي أ...,194,المادة الثلاثون,المادة الثلاثون\nتتولى دائرة الاستئناف -التي أ...,236,0.521,
3,اللائحة التنفيذية لإجراءات الاستئناف,المادة الحاديةعشرة,المادة الحاديةعشرة\nفي الأحوال التي ينظر فيها ...,178,المادة الحاديةعشرة,المادة الحاديةعشرة\nفي الأحوال التي ينظر فيها ...,165,0.939,
4,اللائحة التنفيذية لإجراءات الاستئناف,المادة السابعةوالعشرون,المادة السابعةوالعشرون\nيجب على المحكمة إذا حك...,194,المادة السابعةوالعشرون,المادة السابعةوالعشرون\nيجب على المحكمة إذا حك...,391,0.263,

Manual review cases: 67

In [23]:
from google.colab import files

files.download("manual_duplicate_review.xlsx")

In [24]:
# Keys that require manual verification
manual_keys = set(
    zip(
        manual_review["law_name"],
        manual_review["article_number_1"]
            .str.replace(r'[\s\(\)\.:：]', '', regex=True)
    )
)

def is_manual(row):
    return (row["law_name"], row["article_key"]) in manual_keys

df_articles["needs_manual_review"] = df_articles.apply(is_manual, axis=1)

# Keep clean articles only for the first RAG experiment
df_clean = df_articles[
    ~df_articles["needs_manual_review"]
].copy()

print("All detected articles:", len(df_articles))
print("Excluded for manual review:", df_articles["needs_manual_review"].sum())
print("Clean articles available for RAG:", len(df_clean))

All detected articles: 4367
Excluded for manual review: 134
Clean articles available for RAG: 4233

In [25]:
df_clean = df_clean.sort_values(
    "text",
    key=lambda x: x.str.len(),
    ascending=False
)

df_clean = df_clean.drop_duplicates(
    subset=["law_name", "article_key"],
    keep="first"
)

print("Final clean rows:", len(df_clean))

Final clean rows: 4226

In [26]:
df_clean.to_parquet(
    "saudi_legal_moj_clean.parquet",
    index=False
)

manual_review.to_excel(
    "articles_needing_manual_verification.xlsx",
    index=False
)
print("Saved:", len(df_clean), "rows")

Saved: 4226 rows

In [27]:
!pip install -q sentence-transformers faiss-cpu

In [28]:
df_clean["embedding_text"] = (
    "اسم النظام: " + df_clean["law_name"].astype(str) +
    "\nرقم المادة: " + df_clean["article_number"].astype(str) +
    "\nالنص القانوني: " + df_clean["text"].astype(str)
)

texts = df_clean["embedding_text"].tolist()

print("Number of legal articles:", len(texts))
print("\nExample:\n")
print(texts[0][:700])

Number of legal articles: 4226

Example:

اسم النظام: نظام مكافحة جرائم الإرهاب وتمويله
رقم المادة: المادة الأولى
النص القانوني: المادة الأولى
يقصد بالألفاظ والعبارات الآتية -أينما وردت في هذا النظام- المعاني الموضحة أمام كل منهاء ما لم يقتض السياق خلافذلك:
-١ النظام: نظام مكافحة جرائم الإرهابوتمويله.
-١ اللائحة: اللائحة التنفيذيةللنظام.
؟- الجريمة الإرهابية: كل سلوك يقوم به الجاني تنفيذاً لمشروع إجرامي فردي أو جماعي بشكل مباشر أو غير مباشرء يقصد به الإخلال بالنظام العام» أو زعزعة أمنالمجتمع
واستقرار الدولة أو تعريض وحدتها الوطنية للخطرء أو تعطيل النظام الأساسي للحكم أو بعض أحكامه؛ أو إلحاق الضرر بأحد مرافق الدولة أو مواردها الطبيعية أو الاقتصادية»أو
محاولة إرغام إحدى سلطاتها على القيام بعمل ما أو الامتناع عنه» أو إيذاء أي شخص أو ال

In [29]:
from sentence_transformers import SentenceTransformer
import numpy as np
import faiss

bge_model = SentenceTransformer(
    "BAAI/bge-m3",
    device="cuda"
)

bge_embeddings = bge_model.encode(
    texts,
    batch_size=8,
    show_progress_bar=True,
    normalize_embeddings=True
)

bge_embeddings = np.asarray(
    bge_embeddings,
    dtype="float32"
)

print("Embedding shape:", bge_embeddings.shape)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/123 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/15.8k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/54.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/687 [00:00<?, ?B/s]

pytorch_model.bin: reconstructing file:   0%|          |  0.00B / 2.27GB

pytorch_model.bin: downloading bytes:           |  0.00B

model.safetensors: reconstructing file:   0%|          |  0.00B / 2.27GB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/444 [00:00<?, ?B/s]

sentencepiece.bpe.model: reconstructing file:   0%|          |  0.00B / 5.07MB

sentencepiece.bpe.model: downloading bytes:           |  0.00B

tokenizer.json: reconstructing file:   0%|          |  0.00B / 17.1MB

tokenizer.json: downloading bytes:           |  0.00B

special_tokens_map.json:   0%|          | 0.00/964 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/191 [00:00<?, ?B/s]

Batches:   0%|          | 0/529 [00:00<?, ?it/s]

Embedding shape: (4226, 1024)

In [30]:
bge_index = faiss.IndexFlatIP(
    bge_embeddings.shape[1]
)

bge_index.add(bge_embeddings)

print("BGE documents indexed:", bge_index.ntotal)

BGE documents indexed: 4226

In [31]:
qwen_model = SentenceTransformer(
    "Qwen/Qwen3-Embedding-0.6B",
    device="cuda"
)

qwen_embeddings = qwen_model.encode(
    texts,
    batch_size=8,
    show_progress_bar=True,
    normalize_embeddings=True
)

qwen_embeddings = np.asarray(
    qwen_embeddings,
    dtype="float32"
)

print("Embedding shape:", qwen_embeddings.shape)

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/215 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/17.2k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/727 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 1.19GB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/310 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/9.71k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json: reconstructing file:   0%|          |  0.00B / 11.4MB

tokenizer.json: downloading bytes:           |  0.00B

config.json:   0%|          | 0.00/313 [00:00<?, ?B/s]

Batches:   0%|          | 0/529 [00:00<?, ?it/s]

Embedding shape: (4226, 1024)

In [34]:
qwen_index = faiss.IndexFlatIP(
    qwen_embeddings.shape[1]
)

qwen_index.add(qwen_embeddings)

print("Qwen documents indexed:", qwen_index.ntotal)

Qwen documents indexed: 4226

In [35]:
faiss.write_index(
    bge_index,
    "bge_m3_saudi_legal.index"
)

faiss.write_index(
    qwen_index,
    "qwen3_saudi_legal.index"
)

df_clean.to_parquet(
    "saudi_legal_moj_clean.parquet",
    index=False
)

print("All Stage 1 files saved successfully.")

All Stage 1 files saved successfully.